#!/usr/bin/env bash
#bad luck for various countries
i=0
while ((i <21))
do
    case $i in
	'4')
	    echo bad luck from China;;
	'9')
	    echo bad luck from Japan;;
	'17')
	    echo bad luck from Italy;;
    esac
    ((i++))
    echo $i
done
