#!/usr/bin/env bash
#Gives info about school file
if [ -f school ]
then
    echo school file exists
    if [ -s school ]
    then
	echo school file is not empty
	echo school is a regular file
    else
	echo school file is empty
	echo school is a regular file
    fi
else
    echo school file does not exist
fi
