#!/usr/bin/env bash
#Gives info about school file
if [ -a school ]
then
    echo school file exists
    if [ -s school ]
    then
	echo school file is not empty
	if [ -f school ]
	then
	    echo school is a regular file
	else
	    :
	fi
    else
	echo school file is empty
	if [ -f school ]
	then
	    echo school is a regular file
	else
	    :
	fi
    fi
else
    echo school file does not exist
fi
